* Emacs en français
** Le programme des vidéos

*** Vidéo 0 : Programme, but, installation d'emacs, pourquoi je fais ça et pourquoi Emacs. 

Dire que je le fais en français car l'anglais peut être une barrière pour les débutants,  et bien assez d'info en anglais comme ça. Et je le fais pour des potes donc c'est cool.



Je vais utiliser Keycast (mais pas faire attention aux touches, mais plutôt aux =commandes=!)





Pourquoi cette version ?
Stable, et le 28.0 est en bêta, donc pas stable logiquement et ya des bugs.

Si vous voulez emacs 28 : [[https://git.savannah.gnu.org/cgit/emacs.git/tree/INSTALL][suivre les instructions ici]]

#+begin_src sh
  sudo add-apt-repository ppa:kelleyk/emacs
  sudo apt-get update
  sudo apt install emacs #puis la touche tab pour compléter. prendre la dernière version (27 /27.1/ 27.2 normalement)
  # tester avec cette commande la version d'emacs:
  emacs --version
  # lancer emacs !
  emacs
#+end_src


Liens utiles TODO :

- internet en général, qui est très bien pour la base
- stackoverflow, reddit très bien pour une question précise (en anglais)
- le manuel d'org mode,  pour org mode.
- avec xah (mode commande puis space j) pour écrire ses propre fonction (avancée)
  - describe function/variable
  - customize variable (juste pour savoir ce qu'il faut mettre dedans, mais faire des setq)



[[https://www.youtube.com/channel/UCAiiOTio8Yu69c3XnR7nQBQ][system crafter]]

*** État d'esprit :
**** 1.a Que voit on au démarrage et que se passe t-il en dessous ?

Tool bar mode, les différents buffers ouverts, menu bar mode etc.

on peut faire du code partout, les modes (major et minor), les hooks. exécuter du lisp

Mais où est la configuration ?

    ~/.emacs or ~/.emacs.el - vielle configuration, à supprimer et vraiment pas recommandé
    ~/.emacs.d/init.el - ma version de configuration, 
    ~/.config/emacs/init.el - la meilleur version, mais pas pratique pour faire des test

    Emacs va regarder partout, et dès qu'il en trouve un arrête de chercher
    

**** 1.b et où trouver de l'aide.


*** Comment installer des packages, explication du .emacs.d (base base base d'org mode) (init.el et config .org) 
**** Comment faire une bonne config ? Les if, when, tuto xah lisp. Utiliser la super fonction pour rapidement déboguer (attention de pas mettre de "")
*** Base d'emacs : raccourcis, remapper ses contrôles sur ses pouces, présentation rapide de xah fly key (car c'est celui que j'utilise),

- plusieurs raccourcis possibles :
1. xah-fly-key
2. evil-mode
   une touche un ordre
3. God mode
   C-x C-s = x s
4. General (plusieurs touches, pour chaque mode)
5. key-chord, pour 2 touche une commande ! (ne pas oublier de l'activer)
   #+begin_src emacs-lisp
	   (key-chord-define-global "bb"     'undo)
	   (key-chord-define-global "zb"     'tool-bar-mode)
      (key-chord-define-global "qq"     "the ")
      (key-chord-define-global "QQ"     "The ")
 (key-chord-define c-mode-map "az"  "\C-e;")
 (key-chord-define c-mode-map "{"  "{\n\n}\C-p\t")

#+end_src
6. Cedet ? [[http://cedet.sourceforge.net/][ici]]
7. ryo-modal https://github.com/Kungsgeten/ryo-modal
   #+begin_src emacs-lisp
(modalka-define-kbd "W" "M-w")
(modalka-define-kbd "Y" "M-y")
(modalka-define-kbd "a" "C-a")
(modalka-define-kbd "b" "C-b")
(modalka-define-kbd "e" "C-e")
(modalka-define-kbd "f" "C-f")
(modalka-define-kbd "g" "C-g")
(modalka-define-kbd "n" "C-n")
(modalka-define-kbd "p" "C-p")
(modalka-define-kbd "w" "C-w")
(modalka-define-kbd "y" "C-y")
(modalka-define-kbd "SPC" "C-SPC")
   #+end_src


*** Rendre Emacs convenable (vertico et company + faire ses premieres fonction en lisp), conseiller tuto de xah
*** Emacs et org mode --- Babel, export, formule latex
*** Rendre Emacs efficace pour la programmation
*** Emacs et org mode poussés
*** Ma config en point stratégieque
*** Faire des vidéos sur un nouveau ubuntu pour vraiment montrer comment tout marche (vidéos longues)?
