
* Présentation
:PROPERTIES:
:ID:       71691c9a-a6be-4f76-af75-3eb938f0622b
:END:

Liens vers la playlist youtube : TODO

Liens vers mon .emacs.d : [[https://github.com/Cletip/.emacs.d][ici]]

*But de ce repos*
   Ce repos à pour but de ne pas à avoir à revoir la vidéo. Ces notes ne
   suffisent pas (en théorie), car je donne les explications en vidéo, mais
   permettent d'aller beaucoup plus vite et de se dire "à oui il avait parlé de
   ça, je vais pas revoir la vidéo mais plutôt aller voir les notes". Faites des
   pull-request pour étoffer les notes si vous voulez rajouter des détails :)


** Contexte rapide
Je suis sous un linux, Ubuntu 20.04.3 LTS. (faire "lsb_release -a" pour voir la version)

*** Prérequis : 

1. Avoir les bases de linux : cd, ls, savoir insta
2. Avoir git et savoir les commandes de base et (pas sûr que se soit nécessaire) un compte github pour télécharger des packages.

*** Motivation :

Pourquoi ceci ? Tout simplement pour deux raisons :
1. pour des potes , donc c'est cool.
2. et je trouve qu'il y a un manque de doc en français, car l'anglais peut être
   une barrière pour les débutants. J'ai hésité à le faire en anglais, mais il y
   a bien assez d'info en anglais comme ça.

*** Pourquoi emacs

Emacs est, pour moi, le meilleur "éditeur de texte" pour ces raisons :
- extrèmement modulable et personnalisable via des packages divers et varié
- permet d'aller très très très vite
- n'est pas qu'un simple éditeur de texte ([[https://www.orgmode.org/fr/][org-mode]], faire du code, mails, base de donnée etc)
- éditeur programmable : possibilité d'implémenter ses propres fonctions (niveau intermédiaire)
- fait partie de monde de logiciel libre, gratuit et open-source, ce qui est génial.

Et Vim ? Tout ce qui est dans vim est possible dans emacs, donc go emacs !

** Liens et astuces utiles

*** Les astuces
**** Utiliser M-x pour des commandes peu utilisées
**** Les commandes utiles :
1. describe-function
2. describe-variable
3. straight-visit-package-website
4. dired-jump
5. =xah-pop-local-mark-ring=
6. xah-shrink-whitespaces
7. xah-open-in-external-app
8. xah-open-in-terminal
9. xah-copy-file-path
10. balance-windows

**** Faire des macro
F3, les opérations, puis F4.
*** Les choses pour trouver de l'aide
**** Dans emacs même

- C-h t – Emacs tutorial / xah fly tutoriel
- pour savoir (presque) toutes les touches de xah, SPC C-h.

**** Les liens ailleurs

- stackoverflow évidemment
- le site de xah-fly-key TODO
- le manuel d'org mode,  pour org mode. TODO
- les autres chaînes youtube
  1. [[https://www.youtube.com/channel/UCAiiOTio8Yu69c3XnR7nQBQ][system crafter]]
  2. [[https://cestlaz.github.io/stories/emacs/][C'est la Z]]
